---
output: github_document
---

<!-- README.md är genererad från README.Rmd. Vänligen redigera den filen. -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  collapse = TRUE,
  comment = "#>"
  # fig.path = "man/figures/README-"
)
```

# nkbcgeneral

Planen är att lägga generella verktyg för bearbetning av NKBC-data här.

Den långsiktiga planen är att skapa ett R-paket.

## Installation

```{r, eval = FALSE}
# install.packages("devtools")
# devtools::install_bitbucket("cancercentrum/nkbcgeneral") # inte implementerad än
```

## Användning

```{r}
library(dplyr)
library(tidyr)
library(lubridate)

# library(nkbcgeneral) # inte implementerat än
for (file_name in list.files(pattern = "*.R$")) {
  source(file_name, encoding = "UTF-8")
}
```

Läs in ögonblickskopia av NKBC exporterad från INCA.

```{r}
nkbc_data_dir <- Sys.getenv("NKBC_DATA_DIR")
load(
  unzip(
    file.path(nkbc_data_dir, "2018-08-31", "nkbc_nat_id 2018-08-31 09-22-09.zip"),
    exdir = tempdir()
  )
)
```

Generell förbearbetning av NKBC-data.

```{r}
df_main <- df %>%
  mutate_if(is.factor, as.character) %>%
  clean_nkbc_data() %>%
  mutate_nkbc_d_vars()
```

